const quotes: string[] = [
  'Have a firm handshake.',
  'Look people in the eye.',
  'Sing in the shower.',
  'Own a great stereo system.',
  'Have a firm handshake.',
  'Look people in the eye.',
  'Sing in the shower.',
  'Own a great stereo system.',
  'If in a fight, hit first and hit hard.',
  'Keep secrets.',
  'Never give up on anybody. Miracles happen everyday',
  'Always accept an outstretched hand.',
  'Be brave. Even if you’re not, pretend to be. No one can tell the difference.',
  'Whistle.',
  'Choose your life’s mate carefully. From this one decision will come 90 per cent of all your',
  'happiness or misery.',
  'Make it a habit to do nice things for people who will never find out.',
  'Lend only those books you never care to see again.',
  'Never deprive someone of hope; it might be all that they have.',
  'When playing games with children, let them win.',
  'Give people a second chance, but not a third.',
  'Be romantic.',
  'Become the most positive and enthusiastic person you know.',
  'Loosen up. Relax. Except for rare life-and-death matters, nothing is as important as it first seems.',
  'Don’t allow the phone to interrupt important moments. It’s there for our convenience, not the caller’s.',
  'Be a good loser.',
  'Be a good winner.',
  'Think twice before burdening a friend with a secret.',
  'When someone hugs you, let them be the first to let go.',
  'Be modest. A lot was accomplished before you were born.',
  'Keep it simple.',
  'Beware of the person who has nothing to lose.',
  'Don’t burn bridges. You’ll be surprised how many times you have to cross the same river.',
  'Live your life so that your epitaph could read, No Regrets',
  'Be bold and courageous. When you look back on life, you’ll regret the things you didn’t do more than the ones you did.',
  'Never waste an opportunity to tell someone you love them.',
  'Remember no one makes it alone. Have a grateful heart and be quick to acknowledge those who helped you.',
  'Take charge of your attitude. Don’t let someone else choose it for you.',
  'Visit friends and relatives when they are in hospital; you need only stay a few minutes.',
  'Begin each day with some of your favourite music.',
  'Once in a while, take the scenic route.',
  'Send a lot of Valentine cards. Sign them, ‘Someone who thinks you’re terrific.’',
  'Answer the phone with enthusiasm and energy in your voice.',
  'Keep a note pad and pencil on your bed-side table. Million-dollar ideas sometimes strike at 3 a.m.',
  'Show respect for everyone who works for a living, regardless of how trivial their job.',
  'Send your loved ones flowers. Think of a reason later.',
  'Make someone’s day by paying the toll for the person in the car behind you.',
  'Become someone’s hero.',
  'Marry only for love.',
  'Count your blessings.',
  'Compliment the meal when you’re a guest in someone’s home.',
  'Wave at the children on a school bus.',
  'Remember that 80 per cent of the success in any job is based on your ability to deal with people.',
  'Don’t expect life to be fair',
];

export default quotes;
